services:
  lucos_creds:
    build: server
    container_name: lucos_creds
    hostname: lucos-creds
    ports:
      - "2202:2202"
    image: lucas42/lucos_creds:${VERSION:-latest}
    volumes:
      - "store:/var/lib/creds_store/"
    restart: always
    environment:
      - LOGANNE_ENDPOINT
      - APP_ORIGIN
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 2202"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
  lucos_creds_configy_sync:
    build: configy_sync
    container_name: lucos_creds_configy_sync
    image: lucas42/lucos_creds_configy_sync:${VERSION:-latest}
    restart: always
    environment:
      - SCHEDULE_TRACKER_ENDPOINT
      - CONFIGY_SYNC_PRIVATE_SSH_KEY
    depends_on:
      lucos_creds:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "test -p /var/log/cron.log"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
  lucos_creds_ui:
    build: ui
    container_name: lucos_creds_ui
    ports:
      - $PORT:$PORT
    image: lucas42/lucos_creds_ui:${VERSION:-latest}
    restart: always
    environment:
      - PORT
      - UI_PRIVATE_SSH_KEY
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:${PORT}/_info"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s

volumes:
  store:
